#dev, prod
spring.profiles.active=local
spring.application.name=point

#HARD, SOFT
point.earn.mode=HARD

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.default_batch_fetch_size=100

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.org.springframework.test=info
logging.level.root=info
logging.level.com.musinsa=debug
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.loader.collection=debug
